# Generated by Django 6.0.6 on 2026-06-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('upted_at', models.TimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('disc', models.TextField()),
                ('price', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
