# Generated by Django 5.2.14 on 2026-06-17 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catigory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.TimeField(auto_now_add=True)),
                ("upted_at", models.TimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("icon", models.ImageField(null=True, upload_to="image/catirgory")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.TimeField(auto_now_add=True)),
                ("upted_at", models.TimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("disc", models.TextField()),
                ("price", models.FloatField()),
                (
                    "catigory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.catigory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
