# Generated by Django 6.0.6 on 2026-06-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_catigory_product_catigory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catigory',
            name='icon',
            field=models.ImageField(null=True, upload_to='image/catirgory'),
        ),
    ]
